<a href="https://colab.research.google.com/github/20104042NguyenThiTraMi/study-AI/blob/main/tuan5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)



do chinh xac 1.0
[0 1 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:100]
x= data.drop(['variety'],axis = True)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác', model.score(x_train,y_train))
x_input = [[1,8,4,6],[5,4.6,1.2,10],[2,12,3,4]]
y_output = model.predict(x_input)
print(y_output)

Độ chính xác 1.0
[0 0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0.5,0],[0.9,0.2],[1,0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[0 0 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0,1],[1,0],[0,0],[0,0]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[1 1 0 0]


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test.split
url='/content/crabs.csv'
data=pd.read_csv(url)
x=[[]]
y=
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('Độ chính xác',model.score(x,y))
x_test=[[0.4,0],[-0.5,-0.1],[1,-0.5],[0.9,-0.7]]
y_test=model.predict(x_test)
print(y_test)


Độ chính xác 1.0
[0 1 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/crabs.csv'
data= pd.read_csv(url)
data.loc[data['sex']=='M','sex']='1'
data.loc[data['sex']=='F','sex']='0'
data[(data['speies']=='B')]
x=data.drop(['speies','sex'],axis=True)    
y=data['sex']
model=Perceptron()
model.fit(x,y)
print('độ chính xác',model.score(x,y))
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_test = [[5,6,14,13,10,11],[8,12,7,23,30,33]] 
y_test = model.predict(x_test)
print(y_test)


độ chính xác 0.505
['0' '1']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
data=pd.read_csv('/content/crabs.csv')
data['sex'].replace('M,1')
data['sex'].replace('F,0')
x=data.drop(['speies','sex'],axis=True)
y=data['sex']
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))

do chinh xac 0.505
